; Maps configuration file
; File location: $moddir/addons/amxmodx/configs/maps.ini
; To use with Maps Menu plugin

; Add in your mod's maps here
; Delete this file to use mapcycle.txt

zm_3rooms
zm_assault_remake
zm_aztek
zm_biohazard_base_mx
zm_cpl_egyptian
zm_deko2
zm_five
zm_foda
zm_gbox7
zm_gg
zm_ice_vk
zm_iceworld_humans
zm_laura
zm_orling_base
zm_panichouse_final
zm_snow_volta
zm_terrible_invasion
zm_toronto_remix_v2
zm_zod_dust